spring:
  profiles:
    include: apikey
  datasource:
    url: jdbc:mysql://localhost:3306/kick_wa?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: kick_wa
    password: 3751
    driver-class-name: com.mysql.cj.jdbc.Driver
  #security:
  #  oauth2:
  #    client:
  #      registration:
  #        google:
  #          client-id: 226393017031-v15rgn9759vec6piru7vathpbp7cmnfq.apps.googleusercontent.com
  #          client-secret: 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
  #          scope: email

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
